/**
 * App Catalog Mock Data
 * 
 * Centralized metadata used by the App Catalog, App Launcher, and the
 * new card system. Each entry follows the AppMetadata contract defined
 * in app-catalog-types.ts.
 */

import type { AppMetadata } from './app-catalog-types';

export const APP_CATALOG_DATA: AppMetadata[] = [
  {
    id: 'community-compass',
    slug: 'community-compass',
    name: 'Community Compass',
    phase: 'VOICE',
    category: 'Capacity Building',
    description:
      'Gather community voice through surveys, listening tools, and needs/assets analysis.',
    iconName: 'community-compass',
    status: 'available',
    route: '/community-compass',
    audiences: ['Organization', 'Consultant'],
    focusTags: ['Community listening', 'Stakeholder strategy'],
    isFavorited: true,
  },
  {
    id: 'stakeholdr',
    slug: 'stakeholdr',
    name: 'Stakeholdr',
    phase: 'VOICE',
    category: 'Capacity Building',
    description:
      'Map stakeholders, power, and influence to design smarter engagement and partnership strategies.',
    iconName: 'stakeholdr',
    status: 'available',
    route: '/apps/stakeholdr',
    audiences: ['Consultant', 'Organization'],
    focusTags: ['Stakeholder strategy', 'Community listening'],
  },
  {
    id: 'visionverse',
    slug: 'visionverse',
    name: 'VisionVerse',
    phase: 'INSPIRE',
    category: 'Capacity Building',
    description:
      'Co-create clear mission, vision, and values that align your organization and community.',
    iconName: 'visionverse',
    status: 'beta',
    route: '/apps/visionverse',
    audiences: ['Organization', 'Consultant'],
    focusTags: ['Identity & alignment', 'Innovation design'],
  },
  {
    id: 'thinkgrid',
    slug: 'thinkgrid',
    name: 'ThinkGrid',
    phase: 'INSPIRE',
    category: 'Program Management',
    description:
      'Generate, refine, and compare new program ideas with structured concept testing and AI support.',
    iconName: 'thinkgrid',
    status: 'preview',
    route: '/apps/thinkgrid',
    audiences: ['Multi'],
    focusTags: ['Innovation design', 'Program design'],
    isFavorited: true,
  },
  {
    id: 'pathwaypro',
    slug: 'pathwaypro',
    name: 'PathwayPro',
    phase: 'STRATEGIZE',
    category: 'Program Management',
    description:
      'Turn ideas into logic models, theories of change, and evidence-backed impact pathways.',
    iconName: 'pathwaypro',
    status: 'available',
    route: '/apps/pathwaypro',
    audiences: ['Multi'],
    focusTags: ['Program design', 'Service models'],
  },
  {
    id: 'architex',
    slug: 'architex',
    name: 'Architex',
    phase: 'STRATEGIZE',
    category: 'Program Management',
    description:
      'Design program architecture, service models, and workflows that are ready to implement.',
    iconName: 'architex',
    status: 'available',
    route: '/apps/architex',
    audiences: ['Organization', 'Consultant'],
    focusTags: ['Program design', 'Service models', 'Implementation'],
  },
  {
    id: 'equiframe',
    slug: 'equiframe',
    name: 'EquiFrame',
    phase: 'STRATEGIZE',
    category: 'Capacity Building',
    description:
      'Evaluate equity impacts and embed justice-centered practices across programs and strategies.',
    iconName: 'equiframe',
    status: 'beta',
    route: '/apps/equiframe',
    audiences: ['Organization'],
    focusTags: ['Equity strategy', 'Program design'],
  },
  {
    id: 'fundflo',
    slug: 'fundflo',
    name: 'FundFlo',
    phase: 'STRATEGIZE',
    category: 'Fundraising',
    description:
      'Design diversified revenue models and sustainability plans tied to your programs and portfolio.',
    iconName: 'fundflo',
    status: 'coming-soon',
    route: '/apps/fundflo',
    audiences: ['Multi'],
    focusTags: ['Revenue strategy', 'Financial planning'],
  },
  {
    id: 'launchpath',
    slug: 'launchpath',
    name: 'LaunchPath',
    phase: 'INITIATE',
    category: 'Program Management',
    description:
      'Translate strategy into 90-day implementation plans, milestones, and accountable owners.',
    iconName: 'launchpath',
    status: 'available',
    route: '/apps/launchpath',
    audiences: ['Organization'],
    focusTags: ['Implementation', 'Financial planning'],
  },
  {
    id: 'fundgrid',
    slug: 'fundgrid',
    name: 'FundGrid',
    phase: 'INITIATE',
    category: 'Fundraising',
    description:
      'Build outcome-based budgets, scenarios, and grant-ready financial plans.',
    iconName: 'fundgrid',
    status: 'preview',
    route: '/apps/fundgrid',
    audiences: ['Multi'],
    focusTags: ['Financial planning', 'Revenue strategy'],
  },
  {
    id: 'ops360',
    slug: 'ops360',
    name: 'Ops360',
    phase: 'OPERATE',
    category: 'Program Management',
    description:
      'Coordinate tasks, projects, and workflows to keep day-to-day execution on track.',
    iconName: 'ops360',
    status: 'available',
    route: '/apps/ops360',
    audiences: ['Organization'],
    focusTags: ['Performance visibility', 'Data operations'],
    isFavorited: true,
  },
  {
    id: 'metricmap',
    slug: 'metricmap',
    name: 'MetricMap',
    phase: 'OPERATE',
    category: 'Impact Measurement',
    description:
      'Define KPIs, track outcomes, and visualize performance with connected dashboards.',
    iconName: 'metricmap',
    status: 'available',
    route: '/apps/metricmap',
    audiences: ['Organization'],
    focusTags: ['Performance visibility', 'Data operations'],
  },
  {
    id: 'capacityiq',
    slug: 'capacityiq',
    name: 'CapacityIQ',
    phase: 'OPERATE',
    category: 'Capacity Building',
    description:
      'Assess organizational capacity, benchmark key functions, and identify priority areas for growth.',
    iconName: 'capacityiq',
    status: 'available',
    route: '/apps/capacityiq',
    audiences: ['Organization'],
    focusTags: ['Capacity assessment', 'Benchmarking'],
  },
  {
    id: 'fundingframer',
    slug: 'fundingframer',
    name: 'FundingFramer',
    phase: 'NARRATE',
    category: 'Fundraising',
    description:
      'Generate and manage grant proposals with AI-powered collaboration and review.',
    iconName: 'fundingframer',
    status: 'funder-only',
    route: '/apps/fundingframer',
    audiences: ['Funder', 'Consultant'],
    focusTags: ['Grant writing', 'Narrative support'],
  },
  {
    id: 'narrateiq',
    slug: 'narrateiq',
    name: 'NarrateIQ',
    phase: 'NARRATE',
    category: 'Impact Measurement',
    description:
      'Create compelling impact narratives, concise reports, and board-ready summaries.',
    iconName: 'narrateiq',
    status: 'available',
    route: '/apps/narrateiq',
    audiences: ['Organization'],
    focusTags: ['Impact narratives', 'Reporting'],
  },
];
