import * as React from 'react';
import { format } from 'date-fns';
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';
import { Document as PDFDocument, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer';

export type ExportFormat = 'pdf' | 'docx' | 'markdown';

export interface ExportPersona {
  namePlaceholder?: string;
  ageRange?: string;
  lifeSituation?: string;
  goals: string[];
  barriers: string[];
  strengths: string[];
  supportSystems: string[];
  motivations?: string;
}

export interface ExportData {
  assessment: {
    title: string;
    targetPopulation: string;
    geographicArea: string;
    createdAt: string;
  };
  focusStatement: string;
  selectedChips: Record<string, string[]>;
  empathyMap: {
    painPoints: string[];
    feelings: string[];
    influences: string[];
    intentions: string[];
    narrative: string;
  };
  needs: Array<{
    title: string;
    description: string;
    category: string;
    urgencyLevel: string;
    impactLevel: string;
    evidenceLevel: string;
  }>;
  personas: ExportPersona[];
}

const formatDate = (date: string) => {
  try {
    return format(new Date(date), 'PPP');
  } catch (error) {
    return date;
  }
};

const buildMarkdown = (data: ExportData) => `# ${data.assessment.title}

## Community Assessment Report

**Target Population:** ${data.assessment.targetPopulation}
**Geographic Area:** ${data.assessment.geographicArea}
**Generated:** ${formatDate(data.assessment.createdAt)}

---

## Community Focus Statement

${data.focusStatement || 'No focus statement recorded yet.'}

---

## Community Insights

${Object.entries(data.selectedChips)
  .map(
    ([category, chips]) =>
      `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n${
        chips.length ? chips.map(chip => `- ${chip}`).join('\n') : '- No selections yet.'
      }`
  )
  .join('\n\n')}

---

## Empathy Map

${data.empathyMap.narrative || 'No empathy narrative yet.'}

${Object.entries(data.empathyMap)
  .filter(([key]) => key !== 'narrative')
  .map(
    ([quadrant, items]) =>
      `### ${quadrant.charAt(0).toUpperCase() + quadrant.slice(1).replace(/([A-Z])/g, ' $1')}\n\n${
        Array.isArray(items) && items.length ? items.map((item: string) => `- ${item}`).join('\n') : '- No selections yet.'
      }`
  )
  .join('\n\n')}

---

## Community Needs

${data.needs.length
  ? data.needs
      .map(
        need =>
          `### ${need.title}\n\n${need.description || 'No description provided.'}\n\n**Category:** ${
            need.category
          } | **Urgency:** ${need.urgencyLevel} | **Impact:** ${need.impactLevel} | **Evidence:** ${
            need.evidenceLevel
          }`
      )
      .join('\n\n')
  : '_No needs have been captured yet._'}

---

## Community Personas

${data.personas.length
  ? data.personas
      .map(
        (persona, idx) =>
          `### ${persona.namePlaceholder || `Persona ${idx + 1}`}

- **Age:** ${persona.ageRange || 'Not specified'}
- **Situation:** ${persona.lifeSituation || 'Not specified'}
- **Goals:** ${persona.goals.length ? persona.goals.join(', ') : 'Not specified'}
- **Barriers:** ${persona.barriers.length ? persona.barriers.join(', ') : 'Not specified'}
- **Strengths:** ${persona.strengths.length ? persona.strengths.join(', ') : 'Not specified'}
- **Support Systems:** ${
            persona.supportSystems.length ? persona.supportSystems.join(', ') : 'Not specified'
          }
${persona.motivations ? `- **Motivations:** ${persona.motivations}` : ''}`
      )
      .join('\n\n')
  : '_No personas have been generated yet._'}

---

*Generated by VISION Platform - Community Compass*
`;

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
    backgroundColor: '#F8FAFC',
  },
  section: {
    marginBottom: 20,
  },
  subsection: {
    marginBottom: 12,
    marginLeft: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#0F172A',
  },
  subtitle: {
    fontSize: 14,
    color: '#1E293B',
    marginBottom: 16,
  },
  heading: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 8,
    color: '#0B5FFF', // vision-blue-600 approximation
  },
  subheading: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#0F172A',
  },
  body: {
    fontSize: 12,
    lineHeight: 1.6,
    marginBottom: 8,
    color: '#0F172A',
  },
  bullet: {
    fontSize: 11,
    marginBottom: 4,
    marginLeft: 10,
    color: '#0F172A',
  },
  metadata: {
    fontSize: 10,
    color: '#475569',
    marginBottom: 4,
  },
});

export const exportService = {
  /**
   * Export assessment as PDF
   */
  async exportAsPDF(data: ExportData): Promise<Blob> {
    const PDFDoc = () => (
      <PDFDocument>
        <Page size="A4" style={styles.page}>
          <View style={styles.section}>
            <Text style={styles.title}>{data.assessment.title}</Text>
            <Text style={styles.subtitle}>Community Assessment Report</Text>
            <Text style={styles.metadata}>Target Population: {data.assessment.targetPopulation}</Text>
            <Text style={styles.metadata}>Geographic Area: {data.assessment.geographicArea}</Text>
            <Text style={styles.metadata}>Generated: {formatDate(data.assessment.createdAt)}</Text>
          </View>

          {/* Focus Statement */}
          <View style={styles.section}>
            <Text style={styles.heading}>Community Focus Statement</Text>
            <Text style={styles.body}>{data.focusStatement || 'No focus statement recorded yet.'}</Text>
          </View>

          {/* Selected Insights */}
          <View style={styles.section}>
            <Text style={styles.heading}>Community Insights</Text>
            {Object.entries(data.selectedChips).map(([category, chips]) => (
              <View key={category} style={styles.subsection}>
                <Text style={styles.subheading}>
                  {category.charAt(0).toUpperCase() + category.slice(1)}
                </Text>
                {(chips.length ? chips : ['No selections yet.']).map((chip, idx) => (
                  <Text key={idx} style={styles.bullet}>
                    • {chip}
                  </Text>
                ))}
              </View>
            ))}
          </View>

          {/* Empathy Map */}
          <View style={styles.section}>
            <Text style={styles.heading}>Empathy Map</Text>
            <Text style={styles.body}>{data.empathyMap.narrative || 'No empathy narrative yet.'}</Text>
            {Object.entries(data.empathyMap)
              .filter(([key]) => key !== 'narrative')
              .map(([quadrant, items]) => (
                <View key={quadrant} style={styles.subsection}>
                  <Text style={styles.subheading}>
                    {quadrant.charAt(0).toUpperCase() + quadrant.slice(1).replace(/([A-Z])/g, ' $1')}
                  </Text>
                  {(Array.isArray(items) && items.length ? items : ['No selections yet.']).map((item: string, idx: number) => (
                    <Text key={idx} style={styles.bullet}>
                      • {item}
                    </Text>
                  ))}
                </View>
              ))}
          </View>

          {/* Community Needs */}
          <View style={styles.section}>
            <Text style={styles.heading}>Community Needs</Text>
            {data.needs.length ? (
              data.needs.map((need, idx) => (
                <View key={idx} style={styles.subsection}>
                  <Text style={styles.subheading}>{need.title}</Text>
                  <Text style={styles.body}>{need.description || 'No description provided.'}</Text>
                  <Text style={styles.metadata}>
                    Category: {need.category} | Urgency: {need.urgencyLevel} | Impact: {need.impactLevel} |
                    Evidence: {need.evidenceLevel}
                  </Text>
                </View>
              ))
            ) : (
              <Text style={styles.body}>No needs have been captured yet.</Text>
            )}
          </View>

          {/* Personas */}
          <View style={styles.section}>
            <Text style={styles.heading}>Community Personas</Text>
            {data.personas.length ? (
              data.personas.map((persona, idx) => (
                <View key={idx} style={styles.subsection}>
                  <Text style={styles.subheading}>{persona.namePlaceholder || `Persona ${idx + 1}`}</Text>
                  {persona.ageRange && <Text style={styles.body}>Age: {persona.ageRange}</Text>}
                  {persona.lifeSituation && <Text style={styles.body}>Situation: {persona.lifeSituation}</Text>}
                  <Text style={styles.body}>
                    Goals: {persona.goals.length ? persona.goals.join(', ') : 'Not specified'}
                  </Text>
                  <Text style={styles.body}>
                    Barriers: {persona.barriers.length ? persona.barriers.join(', ') : 'Not specified'}
                  </Text>
                  <Text style={styles.body}>
                    Strengths: {persona.strengths.length ? persona.strengths.join(', ') : 'Not specified'}
                  </Text>
                  <Text style={styles.body}>
                    Support Systems:{' '}
                    {persona.supportSystems.length ? persona.supportSystems.join(', ') : 'Not specified'}
                  </Text>
                  {persona.motivations && <Text style={styles.body}>Motivations: {persona.motivations}</Text>}
                </View>
              ))
            ) : (
              <Text style={styles.body}>No personas have been generated yet.</Text>
            )}
          </View>
        </Page>
      </PDFDocument>
    );

    const blob = await pdf(<PDFDoc />).toBlob();
    return blob;
  },

  /**
   * Export assessment as DOCX
   */
  async exportAsDOCX(data: ExportData): Promise<Blob> {
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            // Title
            new Paragraph({
              text: data.assessment.title,
              heading: HeadingLevel.HEADING_1,
            }),
            new Paragraph({
              text: 'Community Assessment Report',
              heading: HeadingLevel.HEADING_2,
            }),
            new Paragraph({
              children: [new TextRun({ text: `Target Population: ${data.assessment.targetPopulation}` })],
            }),
            new Paragraph({
              children: [new TextRun({ text: `Geographic Area: ${data.assessment.geographicArea}` })],
            }),
            new Paragraph({
              children: [new TextRun({ text: `Generated: ${formatDate(data.assessment.createdAt)}` })],
            }),
            new Paragraph({ text: '' }), // Spacer

            // Focus Statement
            new Paragraph({
              text: 'Community Focus Statement',
              heading: HeadingLevel.HEADING_2,
            }),
            new Paragraph({
              text: data.focusStatement || 'No focus statement recorded yet.',
            }),
            new Paragraph({ text: '' }),

            // Selected Insights
            new Paragraph({
              text: 'Community Insights',
              heading: HeadingLevel.HEADING_2,
            }),
            ...Object.entries(data.selectedChips).flatMap(([category, chips]) => [
              new Paragraph({
                text: category.charAt(0).toUpperCase() + category.slice(1),
                heading: HeadingLevel.HEADING_3,
              }),
              ...(chips.length ? chips : ['No selections yet.']).map(
                chip =>
                  new Paragraph({
                    text: `• ${chip}`,
                    bullet: { level: 0 },
                  })
              ),
            ]),

            // Empathy Map
            new Paragraph({
              text: 'Empathy Map',
              heading: HeadingLevel.HEADING_2,
            }),
            new Paragraph({
              text: data.empathyMap.narrative || 'No empathy narrative yet.',
            }),
            ...Object.entries(data.empathyMap)
              .filter(([key]) => key !== 'narrative')
              .flatMap(([quadrant, items]) => [
                new Paragraph({
                  text: quadrant.charAt(0).toUpperCase() + quadrant.slice(1).replace(/([A-Z])/g, ' $1'),
                  heading: HeadingLevel.HEADING_3,
                }),
                ...(Array.isArray(items) && items.length ? items : ['No selections yet.']).map(
                  (item: string) =>
                    new Paragraph({
                      text: `• ${item}`,
                      bullet: { level: 0 },
                    })
                ),
              ]),

            // Community Needs
            new Paragraph({
              text: 'Community Needs',
              heading: HeadingLevel.HEADING_2,
            }),
            ...(data.needs.length
              ? data.needs.flatMap(need => [
                  new Paragraph({
                    text: need.title,
                    heading: HeadingLevel.HEADING_3,
                  }),
                  new Paragraph({
                    text: need.description || 'No description provided.',
                  }),
                  new Paragraph({
                    text: `Category: ${need.category} | Urgency: ${need.urgencyLevel} | Impact: ${need.impactLevel} | Evidence: ${need.evidenceLevel}`,
                  }),
                ])
              : [new Paragraph({ text: 'No needs have been captured yet.' })]),

            // Personas
            new Paragraph({
              text: 'Community Personas',
              heading: HeadingLevel.HEADING_2,
            }),
            ...(data.personas.length
              ? data.personas.flatMap((persona, idx) => [
                  new Paragraph({
                    text: persona.namePlaceholder || `Persona ${idx + 1}`,
                    heading: HeadingLevel.HEADING_3,
                  }),
                  new Paragraph({ text: `Age: ${persona.ageRange || 'Not specified'}` }),
                  new Paragraph({ text: `Situation: ${persona.lifeSituation || 'Not specified'}` }),
                  new Paragraph({
                    text: `Goals: ${persona.goals.length ? persona.goals.join(', ') : 'Not specified'}`,
                  }),
                  new Paragraph({
                    text: `Barriers: ${persona.barriers.length ? persona.barriers.join(', ') : 'Not specified'}`,
                  }),
                  new Paragraph({
                    text: `Strengths: ${persona.strengths.length ? persona.strengths.join(', ') : 'Not specified'}`,
                  }),
                  new Paragraph({
                    text: `Support Systems: ${
                      persona.supportSystems.length ? persona.supportSystems.join(', ') : 'Not specified'
                    }`,
                  }),
                  persona.motivations
                    ? new Paragraph({ text: `Motivations: ${persona.motivations}` })
                    : new Paragraph({ text: '' }),
                ])
              : [new Paragraph({ text: 'No personas have been generated yet.' })]),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    return blob;
  },

  /**
   * Export assessment as Markdown
   */
  async exportAsMarkdown(data: ExportData): Promise<Blob> {
    const markdown = buildMarkdown(data);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    return blob;
  },
};

export const __internal = {
  buildMarkdown,
};
