-- Seed 15 Engagement Methods

INSERT INTO community_pulse_methods (name, slug, category, description, best_for, group_size_min, group_size_max, duration_min, duration_max, cost_estimate_low, cost_estimate_high, equity_considerations, fit_scores) VALUES

('Focus Groups', 'focus_groups', 'discussion',
 'Facilitated group discussions with 6-12 participants exploring specific topics in depth.',
 'Deep exploration of attitudes, experiences, and perceptions',
 6, 12, 90, 120, 3000, 5000,
 ARRAY['Homogenous groups reduce power dynamics', 'Multiple sessions ensure diverse voices', 'Compensate participants for time'],
 '{"explore": 0.95, "test": 0.6, "decide": 0.4}'::jsonb),

('Listening Sessions', 'listening_sessions', 'discussion',
 'Open community meetings where organizations listen to broad community input and concerns.',
 'Gathering broad community feedback and demonstrating accountability',
 20, 100, 90, 180, 1000, 3000,
 ARRAY['Accessible locations required', 'Provide childcare and translation', 'Multiple sessions at different times'],
 '{"explore": 0.8, "test": 0.5, "decide": 0.6}'::jsonb),

('One-on-One Interviews', 'interviews', 'discussion',
 'In-depth individual conversations for detailed personal stories and sensitive topics.',
 'Collecting detailed narratives and exploring sensitive experiences',
 1, 1, 45, 90, 2000, 4000,
 ARRAY['Build rapport before sensitive questions', 'Offer multiple interview formats', 'Ensure confidentiality'],
 '{"explore": 0.9, "test": 0.7, "decide": 0.3}'::jsonb),

('Community Surveys', 'surveys', 'survey',
 'Structured questionnaires distributed to large numbers of community members.',
 'Gathering quantitative data and reaching large populations',
 100, 10000, 10, 30, 500, 2000,
 ARRAY['Multiple languages required', 'Low-literacy options needed', 'Digital access considerations'],
 '{"explore": 0.5, "test": 0.8, "decide": 0.7}'::jsonb),

('Participatory Workshops', 'workshops', 'workshop',
 'Interactive sessions where participants actively co-create solutions and ideas.',
 'Problem-solving, brainstorming, and co-creating solutions',
 15, 30, 180, 240, 2000, 5000,
 ARRAY['Active facilitation to manage dominance', 'Accessible activities for all abilities', 'Compensate for extended time'],
 '{"explore": 0.7, "test": 0.9, "decide": 0.8}'::jsonb),

('Story Circles', 'story_circles', 'creative',
 'Structured narrative sharing in small groups following cultural protocols.',
 'Building community connection, healing, and sharing lived experience',
 8, 15, 120, 180, 1500, 3000,
 ARRAY['Culturally appropriate protocols', 'Trauma-informed facilitation', 'Create safe space for vulnerability'],
 '{"explore": 0.85, "test": 0.4, "decide": 0.3}'::jsonb),

('Co-Design Labs', 'co_design', 'workshop',
 'Multi-session collaborative design process with community as equal partners.',
 'Designing or redesigning programs, services, or spaces',
 10, 20, 240, 360, 5000, 10000,
 ARRAY['Recognize community expertise', 'Compensate as consultants', 'Share decision-making power'],
 '{"explore": 0.6, "test": 0.95, "decide": 0.85}'::jsonb),

('Walkthroughs & Observations', 'walkthroughs', 'observation',
 'Community members guide observers through spaces to share environmental experiences.',
 'Understanding physical environments and spatial experiences',
 3, 8, 60, 120, 500, 1500,
 ARRAY['Community members as guides', 'Accessible routes required', 'Document with permission'],
 '{"explore": 0.75, "test": 0.6, "decide": 0.4}'::jsonb),

('World Café', 'world_cafe', 'discussion',
 'Large group dialogue with rotating small group conversations at café-style tables.',
 'Cross-pollinating ideas across diverse groups',
 30, 100, 120, 180, 2000, 4000,
 ARRAY['Rotation ensures diverse input', 'Table hosts trained in facilitation', 'Accessible seating arrangements'],
 '{"explore": 0.8, "test": 0.7, "decide": 0.6}'::jsonb),

('Community Forums', 'forums', 'discussion',
 'Public meetings for community input on decisions with structured speaking processes.',
 'Public accountability and democratic decision-making',
 50, 200, 120, 180, 1500, 3500,
 ARRAY['Structured speaking ensures equity', 'Multiple language interpretation', 'Childcare and accessibility'],
 '{"explore": 0.6, "test": 0.6, "decide": 0.9}'::jsonb),

('Asset Mapping', 'asset_mapping', 'creative',
 'Collaborative process to identify community strengths, resources, and capacities.',
 'Identifying community strengths rather than deficits',
 15, 40, 120, 180, 1000, 2500,
 ARRAY['Counter deficit-based narratives', 'Include informal community assets', 'Community defines what counts'],
 '{"explore": 0.85, "test": 0.5, "decide": 0.4}'::jsonb),

('Photovoice', 'photovoice', 'creative',
 'Participants document experiences through photography with narrative explanations.',
 'Visual storytelling and documenting lived experience',
 8, 20, 2880, 4320, 3000, 6000,
 ARRAY['Provide cameras/phones if needed', 'Photo ethics training', 'Community controls image use'],
 '{"explore": 0.9, "test": 0.5, "decide": 0.3}'::jsonb),

('Digital Feedback Platforms', 'digital_feedback', 'digital',
 'Online tools for asynchronous community input through text, audio, or video.',
 'Reaching geographically dispersed communities asynchronously',
 10, 10000, 5, 30, 500, 2000,
 ARRAY['Digital access varies', 'Phone options required', 'Moderation for safety'],
 '{"explore": 0.6, "test": 0.7, "decide": 0.5}'::jsonb),

('Community Visioning', 'visioning', 'workshop',
 'Facilitated sessions where community imagines and articulates desired futures.',
 'Long-term planning and building shared community vision',
 30, 100, 180, 240, 2500, 5000,
 ARRAY['Include marginalized voices in future', 'Multiple sessions for depth', 'Youth and elders both'],
 '{"explore": 0.7, "test": 0.6, "decide": 0.8}'::jsonb),

('Deliberative Dialogue', 'deliberative_dialogue', 'discussion',
 'Structured discussions of complex issues with balanced information and facilitation.',
 'Making informed decisions on complex tradeoffs',
 20, 40, 240, 360, 3000, 6000,
 ARRAY['Neutral information provision', 'Trained facilitators required', 'Diverse participant recruitment'],
 '{"explore": 0.6, "test": 0.7, "decide": 0.95}'::jsonb);
